In [22]:
import pandas as pd
import numpy as np
from mylinearregression import MyLinearRegression as MyLR

data = pd.read_csv("../resources/are_blue_pills_magics.csv")
linear_model1 = MyLR([[89.0], [-8]])
linear_model2 = MyLR([[89.0], [-6]])

Xpill = np.array(data['Micrograms']).reshape(-1,1)
Yscore = np.array(data['Score']).reshape(-1,1)

linear_model1 = MyLR(np.array([[89.0], [-8]]))
linear_model2 = MyLR(np.array([[89.0], [-6]]))
Y_model1 = linear_model1.predict_(Xpill)
Y_model2 = linear_model2.predict_(Xpill)

print(linear_model1.mse_(Y_model1, Yscore))
#print(linear_model2.mse_(Y_model2, Yscore))

[[173795.7603]]


In [23]:
Y_model1

array([[79.64],
       [65.24],
       [62.92],
       [51.48],
       [42.36],
       [41.  ],
       [37.72]])

In [24]:
Xpill

array([[1.17],
       [2.97],
       [3.26],
       [4.69],
       [5.83],
       [6.  ],
       [6.41]])

In [25]:
Yscore

array([[78.93],
       [58.2 ],
       [67.47],
       [37.47],
       [45.65],
       [32.92],
       [29.97]])

In [26]:
Y_model1 = np.insert(Y_model1, 0, 1.0, axis=1)

np.dot(np.transpose(np.dot(Y_model1, linear_model1.theta) - Yscore), np.dot(Y_model1, linear_model1.theta) - Yscore) / Yscore.size

array([[173795.7603]])

In [51]:
a = np.zeros((5,100))

In [52]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.

In [90]:
x = np.array([[2],[1],[2]])
x = np.insert(x, 0, 1.0, axis=1)
np.dot(x, [[1],[2]])

array([[5],
       [3],
       [5]])

In [103]:
data2 = pd.read_csv('../resources/spacecraft_data.csv')
data2

Age  Thrust_power  Terameters  Sell_price
0     0.000000    102.884445   30.117605  768.658817
1     1.144554      9.000000   96.110216   62.450103
2     3.420318     21.804128   11.971169  346.689592
3     3.604186     30.035427   63.635897  255.096497
4     2.660055    129.444990   27.010236  921.303347
..         ...           ...         ...         ...
195  19.367781     95.957785  139.184178   20.000000
196  17.292362    131.718738  102.329786  402.359178
197  17.769504    110.547066  104.018450  260.168988
198  20.000000    178.680560   80.353100  611.782396
199  19.575478    200.000000  200.000000  437.980652

[200 rows x 4 columns]

In [82]:
np.transpose(x)[0]

array([1, 1, 1])

In [93]:
x = np.array(data2[['Age','Thrust_power', 'Terameters']])

In [105]:
x = np.insert(x, 0, 1.0, axis=1)

In [115]:
x

array([[  1.        ,   0.        , 102.88444541,  30.11760461],
       [  1.        ,   1.14455403,   9.        ,  96.11021563],
       [  1.        ,   3.42031828,  21.80412818,  11.97116943],
       [  1.        ,   3.60418627,  30.03542745,  63.63589657],
       [  1.        ,   2.66005498, 129.44499035,  27.01023584],
       [  1.        ,   3.56274012,  74.15338258, 113.55589663],
       [  1.        ,   5.04917884,  89.45919211,  30.02430187],
       [  1.        ,   4.58996677,  47.36653909, 109.01628264],
       [  1.        ,   5.35071551, 113.25376084,  36.23270598],
       [  1.        ,   5.50487713, 104.25410967,  62.02249393],
       [  1.        ,   5.54509617,  67.87312687,  60.18018371],
       [  1.        ,   6.33403523,  64.72275423,  80.86387001],
       [  1.        ,   6.60162032,  67.35006971,  73.02042083],
       [  1.        ,   5.7784424 , 104.7187718 ,   2.0786927 ],
       [  1.        ,   5.1427603 ,  70.10907999,  71.24772305],
       [  1.        ,   5