In [1]:
import numpy as np

def sum_(x, f):
    if x.size == 0:
        return
    res = 0
    for  y in x:
        res += f(y)

    return float(res)

In [72]:
x = np.array([1, 2 , 3])
y = np.array([2, 3, 7])

In [80]:
x * y

array([ 2,  6, 21])

In [69]:
a = np.array([0, 15, -9, 7, 12, 3, -21]).reshape((7,1))
W = np.array([
    [ -8, 8, -6, 14, 14, -9, -4],
    [ 2, -11, -2, -11, 14, -2, 14],
    [-13, -2, -5, 3, -8, -4, 13],
    [ 2, 13, -14, -15, -14, -15, 13],
    [ 2, -1, 12, 3, -7, -3, -6]])
z = np.zeros((W.shape[0], 1))
for x, i in zip(W, range(W.shape[0])):
    z[i] = np.dot(x, a)

In [70]:
z

array([[ 497.],
       [-356.],
       [-345.],
       [-270.],
       [ -69.]])

In [22]:
a = np.array([ 2, -11, -2, -11, 14, -2, 14])
a


array([  2, -11,  -2, -11,  14,  -2,  14])

In [25]:
b = a.reshape(7,1)
dot(a,b)

array([646])

In [81]:
import numpy as np

def dot(x, y):
    if x.size == 0 or y.size == 0 or x.size != y.size:
        return
    res = 0
    for x_i, y_i in zip(x, y):
        res += x_i * y_i
    return (float(res))

def mat_vec_prod(x, y):
    if x.size == 0 or y.size == 0 or x.shape[1] != y.size:
        return
    z = np.ndarray((x.shape[0],1), dtype=int)
    for i, x_i in zip(range(x.shape[0]), x):
        z[i] = dot(x_i, y)
    return z

def mat_mat_prod(x, y):
    if x.size == 0 or y.size == 0 or x.shape[1] != y.shape[0]:
        return
    z = np.zeros((x.shape[0], y.shape[1]), dtype=int)
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            for k in range(x.shape[1]):
                z[i][j] += x[i][k] * y[k][i]
    return z

W = np.array([
    [ -8, 8, -6, 14, 14, -9, -4],
    [ 2, -11, -2, -11, 14, -2, 14],
    [-13, -2, -5, 3, -8, -4, 13],
    [ 2, 13, -14, -15, -14, -15, 13],
    [ 2, -1, 12, 3, -7, -3, -6]])
Z = np.array([
    [ -6, -1, -8, 7, -8],
        [ 7, 4, 0, -10, -10],
        [ 7, -13, 2, 2, -11],
        [ 3, 14, 7, 7, -4],
        [ -1, -3, -8, -4, -14],
        [ 9, -14, 9, 12, -7],
        [ -9, -4, -10, -3, 6]])

mat_mat_prod(W, Z)

array([[  45,   45,   45,   45,   45],
       [-244, -244, -244, -244, -244],
       [  13,   13,   13,   13,   13],
       [-412, -412, -412, -412, -412],
       [ -67,  -67,  -67,  -67,  -67]])

In [147]:
def gradient(x, y, theta):
    if x.size*y.size*theta.size == 0 or x.shape[1] != theta.size or x.shape[0] != y.size:
        return
    z = np.arange(theta.size)
    for j in range(len(theta)):
        res = 0
        for x_i, y_i in zip(x, y):
            res += sum(np.dot(np.dot(theta, x_i) - y_i, x_i ** j))
        z[j] = res
    return z

X = np.array([
    [ -6, -7, -9],
        [ 13, -2, 14],
        [ -7, 14, -1],
        [ -8, -4, 6],
        [ -5, -9, 6],
        [ 1, -5, 11],
        [ 9, -11, 8]])
Y = np.array([2, 14, -13, 5, 12, 4, -19])
Z = np.array([3,0.5,-6])

gradient(X, Y, Z)

array([  -708,  -1730, -45415])

In [114]:
X = np.array([
    [ -6, -7, -9],
        [ 13, -2, 14],
        [ -7, 14, -1],
        [ -8, -4, 6],
        [ -5, -9, 6],
        [ 1, -5, 11],
        [ 9, -11, 8]])
Y = np.array([2, 14, -13, 5, 12, 4, -19])
Z = np.array([3,0.5,-6])
np.dot((np.dot(X[0], Z) - Y[0]), X[0])

array([-183. , -213.5, -274.5])

In [128]:
x = np.arange(3)
x[2] = 42
x

array([ 0,  1, 42])